spring.application.name=service-inventario
# xampp
server.port=8083
spring.datasource.url=jdbc:mysql://localhost:3306/db_inventario?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Ruta donde se generará el JSON de la documentación
springdoc.api-docs.path=/api/v1/inventarios/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
